apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend
    spec:
      containers:
      - name: chat-node-backend
        image: rythmsachdeva54/backend-chatapp:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: "mongodb://root:admin@mongo-db:27017/chatApp?authSource=admin"
        - name: PORT
          value: "5001"
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"


